### ISSUE TITLE
### Wait, where did my books go?

### ISSUE THREAD

**Issue by benspector-mls** [The-Marcy-Lab-School/express-1.2-assignment#1]
This section confused me. What would prompt the fellow to ask this?

@MostlyFocusedMike

**Comment by MostlyFocusedMike** [comment]
I can reword this for sure. Since we're using nodemon, every time they save a file, they lose their server (and their books) so suddenly everything will be gone. Let me be less cute about it

**Comment by MostlyFocusedMike** [comment]
Also, we talked about removing the debug section so I'm commenting that here to make sure I do it
