### ISSUE TITLE
`id` is a string, not a number, in the `req.params` object

### ISSUE THREAD

**Issue by benspector-mls** [The-Marcy-Lab-School/express-1.2-assignment#2]
https://github.com/The-Marcy-Lab-School-Assignments/unit-7-express-1_2-books-benspector-mls#question-3-get-booksid

The `id` from the `req.params` object is going to be a string so fellows will need to `Number` cast the `id` first. Can we give them a reminder about that? Do we want the fellows to debug this on their own?

I can make sure to, in my lecture, emphasize the importance of console.logging the important information from the `req` object...

**Comment by benspector-mls** [comment]
This comes up again in the last `DELETE /books/:id` path as well.

**Comment by MostlyFocusedMike** [comment]
Ah no, I was supposed to warn them about this, I must've edited it out. I debated putting the casting IN the model methods, but I wanted them to hit it (since it's very common).
